AWSTemplateFormatVersion: 2010-09-09
Description: DMS_CHILD - dms replication task
Parameters:
  ReplicationServerARN:
    Default: 'arn:aws:dms:us-east-1:288355943657:rep:KCCEHMX6GD6QGNR3R7XNKMPB3Y'
    NoEcho: 'false'
    Description: Enter ARN of Replication Server to be used
    Type: String
  SourceEndpoint:
    Default: >-
      arn:aws:dms:us-east-1:288355943657:endpoint:B7XYY4UPDLXG24XMTNMZLI2OTP35VEW5OLTSXHQ
    NoEcho: 'false'
    Description: Enter ARN of Source End Point
    Type: String
  TargetEndpoint:
    Default: >-
      arn:aws:dms:us-east-1:288355943657:endpoint:KZJWWWEFEV6T7DYQFXCSMUM7FEF32N26CSG3DWY
    NoEcho: 'false'
    Description: Enter ARN of Target End Point
    Type: String
  ReplicationTaskName:
    Default: >-
      env-en411-dms-task-2-ondemand
    Type: String
Resources:
  DMSPARENT:
    Type: 'AWS::DMS::ReplicationTask'
    Properties:
      SourceEndpointArn: !Ref SourceEndpoint
      TargetEndpointArn: !Ref TargetEndpoint
      ReplicationInstanceArn: !Ref ReplicationServerARN
      ReplicationTaskIdentifier: !Ref ReplicationTaskName
      MigrationType: full-load
      ReplicationTaskSettings:
          !Sub
                  '{
                      "TargetMetadata": {
                        "TargetSchema": "",
                        "SupportLobs": true,
                        "FullLobMode": false,
                        "LobChunkSize": 0,
                        "LimitedSizeLobMode": true,
                        "LobMaxSize": 32,
                        "InlineLobMaxSize": 0,
                        "LoadMaxFileSize": 0,
                        "ParallelLoadThreads": 16,
                        "ParallelLoadBufferSize": 500,
                        "BatchApplyEnabled": false,
                        "TaskRecoveryTableEnabled": false,
                        "ParallelLoadQueuesPerThread": 256,
                        "ParallelApplyThreads": 8,
                        "ParallelApplyBufferSize": 250,
                        "ParallelApplyQueuesPerThread": 120
                      },
                      "FullLoadSettings": {
                        "TargetTablePrepMode": "DROP_AND_CREATE",
                        "CreatePkAfterFullLoad": false,
                        "StopTaskCachedChangesApplied": false,
                        "StopTaskCachedChangesNotApplied": false,
                        "MaxFullLoadSubTasks": 8,
                        "TransactionConsistencyTimeout": 600,
                        "CommitRate": 10000
                      },
                      "Logging": {
                        "EnableLogging": true,
                        "LogComponents": [
                          {
                            "Id": "TRANSFORMATION",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "SOURCE_UNLOAD",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "IO",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "TARGET_LOAD",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "PERFORMANCE",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "SOURCE_CAPTURE",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "SORTER",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "REST_SERVER",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "VALIDATOR_EXT",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "TARGET_APPLY",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "TASK_MANAGER",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "TABLES_MANAGER",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "METADATA_MANAGER",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "FILE_FACTORY",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "COMMON",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "ADDONS",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "DATA_STRUCTURE",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "COMMUNICATION",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          },
                          {
                            "Id": "FILE_TRANSFER",
                            "Severity": "LOGGER_SEVERITY_DEFAULT"
                          }
                        ]
                        
                      },
                      "ControlTablesSettings": {
                        "historyTimeslotInMinutes": 5,
                        "ControlSchema": "",
                        "HistoryTimeslotInMinutes": 5,
                        "HistoryTableEnabled": false,
                        "SuspendedTablesTableEnabled": false,
                        "StatusTableEnabled": false
                      },
                      "StreamBufferSettings": {
                        "StreamBufferCount": 3,
                        "StreamBufferSizeInMB": 8,
                        "CtrlStreamBufferSizeInMB": 5
                      },
                      "ChangeProcessingDdlHandlingPolicy": {
                        "HandleSourceTableDropped": true,
                        "HandleSourceTableTruncated": true,
                        "HandleSourceTableAltered": true
                      },
                      "ErrorBehavior": {
                        "DataErrorPolicy": "LOG_ERROR",
                        "DataTruncationErrorPolicy": "LOG_ERROR",
                        "DataErrorEscalationPolicy": "SUSPEND_TABLE",
                        "DataErrorEscalationCount": 0,
                        "TableErrorPolicy": "SUSPEND_TABLE",
                        "TableErrorEscalationPolicy": "STOP_TASK",
                        "TableErrorEscalationCount": 0,
                        "RecoverableErrorCount": -1,
                        "RecoverableErrorInterval": 5,
                        "RecoverableErrorThrottling": true,
                        "RecoverableErrorThrottlingMax": 1800,
                        "ApplyErrorDeletePolicy": "IGNORE_RECORD",
                        "ApplyErrorInsertPolicy": "LOG_ERROR",
                        "ApplyErrorUpdatePolicy": "LOG_ERROR",
                        "ApplyErrorEscalationPolicy": "LOG_ERROR",
                        "ApplyErrorEscalationCount": 0,
                        "ApplyErrorFailOnTruncationDdl": false,
                        "FullLoadIgnoreConflicts": true,
                        "FailOnTransactionConsistencyBreached": false,
                        "FailOnNoTablesCaptured": false
                      },
                      "ChangeProcessingTuning": {
                        "BatchApplyPreserveTransaction": true,
                        "BatchApplyTimeoutMin": 1,
                        "BatchApplyTimeoutMax": 30,
                        "BatchApplyMemoryLimit": 500,
                        "BatchSplitSize": 0,
                        "MinTransactionSize": 1000,
                        "CommitTimeout": 1,
                        "MemoryLimitTotal": 1024,
                        "MemoryKeepTime": 60,
                        "StatementCacheSize": 50
                      }
                  }'
              
            
      TableMappings: 
        "{
          \"rules\": [
            {
              \"rule-type\": \"transformation\",
              \"rule-id\": \"1\",
              \"rule-name\": \"1\",
              \"rule-target\": \"schema\",
              \"object-locator\": {
                \"schema-name\": \"%\"
              },
              \"rule-action\": \"convert-lowercase\"
              
            },
            {
              \"rule-type\": \"selection\",
              \"rule-id\": \"2\",
              \"rule-name\": \"2\",
              \"object-locator\": {
                \"schema-name\": \"PSWMS\",
                \"table-name\": \"TWMWR\"
              },
              \"rule-action\": \"include\",
              \"filters\": []
            }
          ]
        }"
      Tags:
        - Key: ResourceOwner
          Value: sree.suragowni@fpl.com
        - Key: EnvironmentType
          Value: Development
        - Key: AppCode
          Value: EN411

Outputs:
  StackName:
    Value: !Ref 'AWS::StackName'
  Regionname:
    Value: !Ref 'AWS::Region'
  SourceEndPoint:
    Value: !Ref SourceEndpoint
  TargetEndPoint:
    Value: !Ref TargetEndpoint
  ReplicationTaskName:
    Value: !Ref ReplicationTaskName
    Description: Replication Task Name
