#################################################################################
# IAM Template
# Created by: Cedric El Khoury
# Date: 10/29/2020
# Jira:
##################################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: Amazon EKS nodes IAM role
###############################
# CFT Parameters
###############################
Parameters:
  Environment:
    Description: 'Select the environment for which this is being deployed'
    Type: String
    AllowedValues:
      - Enterprise-Non-Prod
      - EnterpriseQA
      - EnterpriseProd
  AppCode:
    Type: String
    MaxLength: "5"
    AllowedPattern: "^([A-Z0-9_-]){5}$"
    Description: "Please enter your 5 digit AppCode"
    ConstraintDescription: "Appcode field does not match the required constraints"
    Default: ST503

  AppCodeLower:
    Type: String
    MaxLength: '5'
    AllowedPattern: "^([a-z0-9_-]){5}$"    
    Description: 'The application code name cannot be of more that 5 characters e.g: en411'
    ConstraintDescription: "Appcode field does not match the required constraints"   
    Default: st503

  Requestor:
    Type: String
    Description: Please specify email address of the requestor
    AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
    ConstraintDescription: Requestor field must be an email address
    Default: Cedric.Elkhoury@fpl.com
    
  OwnerContact:
    Type: String
    Description: Please specify email address of the owner
    AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
    ConstraintDescription: Requestor field must be an email address
    Default: Nelson.Castellanos@fpl.com   

  UserContact:
    Type: String
    Description: Please specify email address of the usercontact
    AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
    ConstraintDescription: Requestor field must be an email address   

  Purpose:
    Type: String
    Description: Please specify the purpose
    Default: Amazon EKS cluster role

  Project:
    Type: String
    Description: Please specify the Project
    Default: Starburst

  Environment:
    Type: String
    AllowedValues:
      - Dev
      - Test
      - QA
      - Prod
      - DR

  DataClassification:
    Type: String
    Description: Please specify the Data Classification
    Default: TBD 

  ITArea:
    Type: String
    Description: Please specify the IT Area
    Default: NELSON CASTELLANOS-305-552-3533-NXC0GLT

  SupportContact:
    Type: String
    Description: Please specify the Support Contact
    Default: NELSON CASTELLANOS-305-552-3533-NXC0GLT

  SupportGroup:
    Type: String
    Description: Please specify the Support Group
    Default: IT-EDP-PLATFORM 

###############################
# CFT Mappings
###############################

Mappings:
  RegionMap:
      us-east-1:
        Region: V
        RegionLower: v
      us-east-2:
        Region: O
        RegionLower: o  

###############################
# CFT Resources
###############################

Resources:

   NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      RoleName: !Join [ "-", [ !Join ["",['2', !ImportValue Account-Global-AccountCodeLower, !FindInMap [RegionMap, !Ref "AWS::Region", RegionLower]]], !Ref AppCodeLower, eks-nodegroups-role ]]
      Tags:
        - Key: AppCode
          Value: !Ref AppCode
        - Key: Environment
          Value: !Ref Environment
        - Key: DataClassification
          Value: !Ref DataClassification
        - Key: ITArea
          Value: !Ref ITArea
        - Key: SupportContact
          Value: !Ref SupportContact
        - Key: SupportGroup
          Value: !Ref SupportGroup
        - Key: IamRoleName
          Value: !Join [ "-", [ !Join ["",['2', !ImportValue Account-Global-AccountCodeLower, !FindInMap [RegionMap, !Ref "AWS::Region", RegionLower]]], !Ref AppCodeLower, eks-nodegroups-role ]]
        - Key: IamRoleBU
          Value: NotApplicable
        - Key: Purpose
          Value: !Ref Purpose
        - Key: CloudformationStackName
          Value: !Sub "${AWS::StackName}"
        - Key: UserContact
          Value: !Ref UserContact
        - Key: ADGroup
          Value: NotApplicable
        - Key: PolicyAttached1
          Value: 'AmazonEKSWorkerNodePolicy'
        - Key: PolicyAttached2
          Value: 'AmazonEKS_CNI_Policy'
        - Key: PolicyAttached3
          Value: 'AmazonEC2ContainerRegistryReadOnly'
        - Key: PolicyAttached4
          Value: NotApplicable
        - Key: PolicyAttached5
          Value: NotApplicable
        - Key: PolicyAttached6
          Value: NotApplicable
        - Key: PolicyAttached7
          Value: NotApplicable
        - Key: PolicyAttached8
          Value: NotApplicable
        - Key: PolicyAttached9
          Value: NotApplicable
        - Key: PolicyAttached10
          Value: NotApplicable  

# ==============================
# CF Template OUTPUTS
# ==============================

Outputs:
  
  RoleArn:
    Description: The role that Amazon EKS node instances will be using
    Value: !GetAtt  NodeInstanceRole.Arn
