###########################################################################################
# AWS CloudFormation Template that provisions Windows EC2 instance using NEE approved AMI
# Base template created by CAEE team
# Base template creation date: 05/23/2018
# <Team Name> team using for <Application Name> <NEECode>
# Last modified date: <date>
# Last change: <change>
#
############################################################################################

AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template that provisions Windows EC2 instance using NEE approved AMI

####################################### Parameters ##########################################

Parameters:

  AppCode:
    Type: String
    MaxLength: 5
    AllowedPattern: ^([A-Z0-9_-]){5}$
    Description: The application code name (NEECode) cannot be of more that 5 characters
    ConstraintDescription: Appcode field does not match the required constraints

  Environment:
    Type: String
    AllowedValues:
      - Dev
      - Test
      - QA
      - Prod
      - DR
    Default: Dev

  InstanceType:
    Type: String
    Description: EC2 instance type, default is t2.micro
    ConstraintDescription: Must be a valid EC2 instance type.
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - t3a.nano
      - t3a.micro
      - t3a.small
      - t3a.medium
      - t3a.large
      - t3a.xlarge
      - t3a.2xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - c1.medium
      - c1.xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - g2.2xlarge
      - g2.8xlarge
      - r3.large
      - r3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r4.16xlarge
      - i2.xlarge
      - i2.2xlarge
      - i2.4xlarge
      - i2.8xlarge
      - d2.xlarge
      - d2.2xlarge
      - d2.4xlarge
      - d2.8xlarge
    Default: t2.micro

  TypeOfInstance:
    Type: String
    Description: 'GC-General Compute App Server, Web Server /RD -RDS database /DB -EC2 database /AP -Appliance (firewall, loadbalancer, etc.) /BS -Beanstalk /CS -Container Service /DC-Domain Controller /EM -Elastic Map Reduce /RS -Redshift'
    AllowedValues:
      - GC
      - RD
      - DB
      - AP
      - BS
      - CS
      - AD
      - EM

  AvailabilityZone:
    Type: String
    AllowedValues:
      - a
      - b
      - c
    Default: a
    Description: Please specify the Availability Zone for your instances, some env may not have c

  OperatingSystem:
    Type: String
    AllowedValues:
      - Windows-2012R2-Base
      - Windows-2016-Base
    Description: Please select Windows Version

  HADRTier:
    Type: String
    AllowedValues:
      - 1
      - 2
      - 3
      - 4
      - 5
    Default: 5
    Description: Please specify the DR tier for your instance

  ApplicationTier:
    Type: String
    AllowedValues:
      - App
      - DataBase
      - Visibility
      - White
      - Lambda
      - Prime
    Default: App
    Description: Please, select in which subnet the servers will reside

  AutomateShutdown:
    Type: String
    Description: This field specifies if the server needs to be automatically shut down every day
    AllowedValues:
      - yes
      - no
    Default: yes

  HostNumber:
    Type: String
    AllowedPattern: "^([0-9]){2}$"
    Description: Please assigned a number for this EC2 instance between 01 and 99. Please make sure it is unique
    ConstraintDescription: Hostnumber field has to be a 2 digit number between 01 and 99

  SetTerminationProtection:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false

  VPCShortName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/account/VPCShortName'

####################################### Mappings ############################################
Mappings:
  # Mappings for AMI ID information based on OS
  OSMap:
    Windows-2012R2-Base:
      useast1: ami-036f813a94ceb185c
      #useast2: ami-092a1e15261417967
      HdSize: 80
      OSType: WINDOWS
      DeviceName: /dev/sda1
    Windows-2016-Base:
      useast1: ami-0a57bf2300a4473f9
      useast2: ami-0d948a50d640b5664
      HdSize: 80
      OSType: WINDOWS
      DeviceName: /dev/sda1

  # Mappings for Availability zones
  AZMap:
    zone:
      a: A
      b: B
      c: C

  # Mappings for Region
  RegionMap:
    us-east-1:
      Region: useast1
    us-east-2:
      Region: useast2

####################################### Conditions #####################################
Conditions:
  IsDR: !Equals [!Ref 'AWS::Region', 'us-east-2']

####################################### Resources #######################################

Resources :
 #EBS Volume
  EBSVol01:
    Type: "AWS::EC2::Volume"
    Properties:
     AvailabilityZone: !Join
        - ''
        - - !Ref "AWS::Region"
          - !Ref AvailabilityZone
     Size: 128
     VolumeType: gp2
     Encrypted: True
     KmsKeyId: !ImportValue Host-Default-KMS
    DeletionPolicy: Snapshot

 # Elastic network inteface
  ENI01:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId:
        Fn::ImportValue:
          !Join ['-', ['VPC', !Ref VPCShortName, !FindInMap [ AZMap, zone, !Ref AvailabilityZone ], !Ref ApplicationTier,'SUBNET']]
      Description: Elastic network interface for ec2 instance
      GroupSet:
        - Fn::ImportValue:
            !Join ['-',[ 'SG', !Ref VPCShortName, 'L1SG' ] ]
        - Fn::ImportValue:
            !Join ['-',[ 'SG', !Ref VPCShortName, 'L2WINSG' ] ]
      SourceDestCheck: True
      Tags:
        - Key: AppCode
          Value: !Ref AppCode
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - Fn::Join:
                  - ''
                  - - '2'
                    - !ImportValue  Account-Global-AccountCode
                    - Fn::ImportValue:
                        !Join ['-',[Account-Global-RegionCode, !Ref 'AWS::Region']]
                - !Ref TypeOfInstance
                - !Join ['',[ !Ref AppCode, !Ref HostNumber ]]
                - 'ENI'

  #EC2 Instance
  EC2Instance01:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: NEE-EC2-ITAM-Role
      DisableApiTermination: !Ref SetTerminationProtection
      InstanceType: !Ref InstanceType
      ImageId: !If
        - IsDR
        - !FindInMap [ OSMap , !Ref OperatingSystem, !FindInMap [RegionMap, !Ref 'AWS::Region', Region] ]
        - !FindInMap [ OSMap , !Ref OperatingSystem, !FindInMap [RegionMap, !Ref 'AWS::Region', Region] ]
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref ENI01
          DeviceIndex: '0'
      AvailabilityZone: !Join
        - ''
        - - !Ref 'AWS::Region'
          - !Ref AvailabilityZone
      BlockDeviceMappings:
        - DeviceName: !FindInMap [ OSMap , !Ref OperatingSystem, DeviceName ]
          Ebs:
            VolumeType: gp2
            VolumeSize: !FindInMap [ OSMap , !Ref OperatingSystem, HdSize ]
      Volumes:
        -
          VolumeId: !Ref EBSVol01
          Device: /dev/xvdb
      UserData:
        Fn::Base64:
          Fn::Sub:
          - |
            #cloud-config
            runcmd:
            "<script> powershell.exe "C:\Temp\DomainJoin.ps1"</script>"
          - {}
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - Fn::Join:
                  - ''
                  - - "2"
                    - !ImportValue  Account-Global-AccountCode
                    - Fn::ImportValue:
                        !Join ['-',[Account-Global-RegionCode, !Ref 'AWS::Region']]
                - !Ref TypeOfInstance
                - !Join ['',[ !Ref AppCode, !Ref HostNumber ]]
        - Key: AppCode
          Value: !Ref AppCode
        - Key: Environment
          Value: !Ref Environment
        - Key: OS
          Value: !FindInMap [ OSMap , !Ref OperatingSystem, OSType ]
        - Key: HA_DRTier
          Value: !Ref HADRTier
        - Key: ApplicationTier
          Value: !Ref ApplicationTier
        - Key: AutomateShutdown
          Value: !Ref AutomateShutdown

####################################### Outputs ##########################################
Outputs:
  EC2Instance01HostName:
    Description: Ec2 instance hostname
    Value:
      Fn::Join:
              - '-'
              - - Fn::Join:
                  - ''
                  - - '2'
                    - !ImportValue  Account-Global-AccountCode
                    - Fn::ImportValue:
                        !Join ['-',[Account-Global-RegionCode, !Ref 'AWS::Region']]
                - !Ref TypeOfInstance
                - !Join ['',[ !Ref AppCode, !Ref HostNumber ]]

  Ec2IP:
    Description: Ec2 instance ipadress
    Value: !GetAtt EC2Instance01.PrivateIp

  Ec2PriDns:
    Description: Ec2 instance pviatedns
    Value: !GetAtt EC2Instance01.PrivateDnsName