####################################################################################
# Template to create SNS for the Posts App
# Created by: Soni Mirani
# Environment: FPL Sandbox
# Date: 04/Dec/2019
####################################################################################

AWSTemplateFormatVersion: 2010-09-09
Description: Cloud Formation Template for POSTAL SNS

############################################################
### Parameters
############################################################

Parameters:
  AppCode:
    Type: String
    MaxLength: '5'
    AllowedPattern: '^([a-zA-Z0-9_-]){5}$'
    Description: The application code name cannot be of more that 5 characters
    ConstraintDescription: Appcode field does not match the required constraints
    Default: PO164
  AppCodeLower:
    Type: String
    MaxLength: '5'
    AllowedPattern: '^([a-zA-Z0-9_-]){5}$'
    Description: >-
      The application code name cannot be of more that 5 characters and should
      be lower
    Default: po164
  RequestorSLID:
    Type: String
    Description: Please specify SLID of the requestor for notification purposes.
    Default: sxm0a2i
  VPCShortName:
    Type: String
    AllowedValues:
      - EnterpriseProd
      - Core
      - CoreTest
      - DMZ
      - EnterpriseDev
      - EnterpriseProd
      - EnterpriseQA
      - EnterpriseSandbox
      - EnterpriseTest
      - FPLDev
      - FPLProd
      - FPLQA
      - FPLSandbox
      - FPLTest
      - IsolateSandbox
      - NEERDev
      - NEERProd
      - NEERQA
      - NEERSandbox
      - NEERTest
      - Security
      - SecurityTest
      - VDI
      - VDIDR
      - VDITest
    Default: FPLDev
  BusinessUnit:
    Type: String
    Default: Customer Service
  Department:
    Type: String
    Default: CSIT
  CostCenter:
    Type: String
  IOWBS:
    Type: String
  OwnerContact:
    Type: String
    Default: sxm0a2i
  Environment:
    Description: Define the environment in which this lambda function will be exectued
    Type: String
    AllowedValues:
      - Prod
      - Test
      - Dev
      - QA
      - DR
      - Sandbox
    Default: QA
  SNSTopicName:
    Type: String
    Description: The name of the SNS Topic that you will be creating
    Default: 2QPV-SNS-PO164-EMR-Topic
  Protocol:
    Description: Define the subscription protocol to be used
    Type: String
    AllowedValues:
      - http
      - https
      - email
      - email-json
      - sms
      - sqs
      - application
      - lambda
    Default: email-json
  Endpoint:
    Description: >-
      The endpoint that you want to receive notifications. Please ensure the
      ENDPOINT pertains to the PROTOCOL selected.
    Type: String
    Default: cs-data-process-reports-dev@fpl.com

############################################################
### Mappings
############################################################	

Mappings:
  RegionMap:
    us-east-1:
      Region: V
      RegionLower: v
    us-east-2:
      Region: O
      RegionLower: o
  AZMap:
    zone:
      a: A
      b: B
      c: C
  ResourceTierMap:
    App:
      ResourceCode: App
    DataBase:
      ResourceCode: DB
    Web:
      ResourceCode: Web
    Prime:
      ResourceCode: Prime
    DMZ:
      ResourceCode: DMZ
    Public:
      ResourceCode: Public
    Lambda:
      ResourceCode: Lambda

############################################################
### Resources
############################################################

Resources:
# SNS Topic Creation  
  POSTALAppAlerts:
    Type: 'AWS::SNS::Topic'
    Properties:
      KmsMasterKeyId: !ImportValue Host-Default-KMS
      TopicName: !Join 
        - '-'
        - - !Join 
            - ''
            - - 2
              - 
          - !Ref AppCode
          - !Ref SNSTopicName
          - SNS
              
          
# SNS Topic Subcription   
  POSTALAppAlertsSub:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !Ref Endpoint
      Protocol: !Ref Protocol
      Region: !Ref 'AWS::Region'
      TopicArn: !Ref POSTALAppAlerts

############################################################
### Outputs
############################################################
Outputs:
  POSTALAppAlertsTopic:
    Description: SNS Topic Name
    Value: !Ref POSTALAppAlerts
    Export:
      Name: !Sub 'POSTAL-${AppCode}-${Protocol}-SNSAlertingTopic'